FROM mysql:8.0

# Environment variables (same as docker-compose)
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=todo_db

# Expose MySQL port
EXPOSE 3306

# MySQL image already has correct ENTRYPOINT & CMD